### ISSUE TITLE
0.3.3 Crashes on your latest update with error 'Flix2Kodi crashed: Try to refresh your login'

### ISSUE THREAD

**Issue by jaraeez** [logi85/plugin.video.flix2kodi#11]
11:51:17 T:140735259591424   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.flix2kodi/?mode=search&thumb&type=tv&url) failed
11:51:17 T:4606070784  NOTICE: Thread LanguageInvoker start, auto delete: false
11:51:17 T:4606070784  NOTICE: -->Python Interpreter Initialized<--
11:51:17 T:4611493888  NOTICE: Thread BackgroundLoader start, auto delete: false
11:51:29 T:4606070784  NOTICE: Thread LanguageInvoker start, auto delete: false
11:51:29 T:4606070784  NOTICE: -->Python Interpreter Initialized<--
11:51:29 T:4606070784  NOTICE: [plugin.video.flix2kodi] parameters: ?mode=list_videos&thumb&type=tv&url=my-list
11:51:29 T:4606070784   ERROR: [plugin.video.flix2kodi] Traceback (most recent call last):
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/addon.py", line 82, in <module>
                                                handle_request()
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/addon.py", line 40, in handle_request
                                                list.videos(url, video_type, page, run_as_widget)
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/list.py", line 26, in videos
                                                video_ids = get.videos_matches(video_type, page, url)
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/get.py", line 29, in videos_matches
                                                read_mylists()
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/get.py", line 295, in read_mylists
                                                content = connect.load_netflix_site("https://www.netflix.com/")
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/connect.py", line 91, in load_netflix_site
                                                session.headers = read_headers()
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/connect.py", line 80, in read_headers
                                                return pickle.loads(content)
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/pickle.py", line 1374, in loads
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/pickle.py", line 858, in load
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/pickle.py", line 880, in load_eof
                                            EOFError
11:51:35 T:140735259591424   ERROR: GetDirectory - Error getting plugin://plugin.video.flix2kodi/?mode=list_videos&thumb&type=tv&url=my-list
11:51:35 T:140735259591424   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.flix2kodi/?mode=list_videos&thumb&type=tv&url=my-list) failed
11:51:35 T:4606070784  NOTICE: Thread LanguageInvoker start, auto delete: false
11:51:35 T:4606070784  NOTICE: -->Python Interpreter Initialized<--
11:51:35 T:4611493888  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by logi85** [comment]
please try to delete cookies in settings.

**Comment by jaraeez** [comment]
Completely removed old working version (which I modified) & installed your latest one.
Reset & tried to remove cookies though had same error.. whereby nothing happens.


11:45:07 T:4508762112  NOTICE: Thread LanguageInvoker start, auto delete: false
11:45:07 T:4508762112  NOTICE: -->Python Interpreter Initialized<--
11:45:08 T:4508762112  NOTICE: [plugin.video.flix2kodi] Cache folder deleted.
11:45:10 T:4508762112  NOTICE: Thread LanguageInvoker start, auto delete: false
11:45:10 T:4508762112  NOTICE: -->Python Interpreter Initialized<--
11:45:13 T:4508762112  NOTICE: [plugin.video.flix2kodi] Addon userdata folder deleted.
11:45:32 T:4508762112  NOTICE: Thread LanguageInvoker start, auto delete: false
11:45:32 T:4508762112  NOTICE: -->Python Interpreter Initialized<--
11:45:32 T:4508762112  NOTICE: [plugin.video.flix2kodi] Cache folder deleted.
11:45:33 T:4508762112  NOTICE: Thread LanguageInvoker start, auto delete: false
11:45:33 T:4508762112  NOTICE: -->Python Interpreter Initialized<--
11:45:33 T:4508762112  NOTICE: [plugin.video.flix2kodi] Cache folder deleted.
11:45:34 T:4508762112  NOTICE: Thread LanguageInvoker start, auto delete: false
11:45:34 T:4508762112  NOTICE: -->Python Interpreter Initialized<--
11:45:34 T:4508762112  NOTICE: [plugin.video.flix2kodi] parameters: ?mode=delete_cookies
11:45:34 T:4508762112   ERROR: [plugin.video.flix2kodi] Traceback (most recent call last):
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/addon.py", line 82, in <module>
                                                handle_request()
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/addon.py", line 64, in handle_request
                                                delete.cookies()
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/delete.py", line 30, in cookies
                                                if xbmcvfs.exists(generic_utility.cookie_file()):
                                            AttributeError: 'module' object has no attribute 'cookie_file'
11:45:38 T:4508762112   ERROR: /Users/user1/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
11:45:38 T:4508762112   ERROR: /Users/user1/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/packages/urllib3/connection.py:266: SubjectAltNameWarning: Certificate for www.netflix.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
                                              SubjectAltNameWarning
11:45:39 T:4508762112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.EOFError'>
                                            Error Contents: 
                                            Traceback (most recent call last):
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/addon.py", line 89, in <module>
                                                if login.login()==True:
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/login.py", line 31, in login
                                                post=post_data)
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/connect.py", line 91, in load_netflix_site
                                                session.headers = read_headers()
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/connect.py", line 80, in read_headers
                                                return pickle.loads(content)
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/pickle.py", line 1374, in loads
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/pickle.py", line 858, in load
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/pickle.py", line 880, in load_eof
                                            EOFError
                                            -->End of Python script error report<--

**Comment by logi85** [comment]
ok, please try again deleting cookies with 0.4.2 (there was a bug in 0.4.1)

**Comment by jaraeez** [comment]
OK cookies seemed to get deleted but same issue.


                                              SubjectAltNameWarning
01:22:56 T:4556849152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.EOFError'>
                                            Error Contents: 
                                            Traceback (most recent call last):
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/addon.py", line 89, in <module>
                                                if login.login()==True:
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/login.py", line 31, in login
                                                post=post_data)
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/connect.py", line 91, in load_netflix_site
                                                session.headers = read_headers()
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/connect.py", line 80, in read_headers
                                                return pickle.loads(content)
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/pickle.py", line 1374, in loads
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/pickle.py", line 858, in load
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/pickle.py", line 880, in load_eof
                                            EOFError
                                            -->End of Python script error report<--
01:22:57 T:140735259591424   ERROR: GetDirectory - Error getting plugin://plugin.video.flix2kodi/?mode=main&thumb&type=tv&url
01:22:57 T:140735259591424   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.flix2kodi/?mode=main&thumb&type=tv&url) failed
01:22:57 T:4556849152  NOTICE: Thread LanguageInvoker start, auto delete: false
01:22:57 T:4556849152  NOTICE: -->Python Interpreter Initialized<--
01:22:57 T:4557385728  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by logi85** [comment]
please have a look on /Users/<your_user_name>/Library/Application Support/Kodi/userdata/ addon_data/plugin.video.flix2kodi/ is there a file called "headers" and/or "cookies" after clearing from settings?
If these files are still there, please remove them and login again (from main menu select relogin in context-menu) hope this helps

**Comment by jaraeez** [comment]
Cheers.

Completely removed it then installed latest & added login details etc. It does remove both headers" and "cookies but when i do a relogin I get the same error 'flix2kodi crashed etc.

Once I put the old one back all works again except for the search etc.

02:40:50 T:4593389568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.EOFError'>
                                            Error Contents: 
                                            Traceback (most recent call last):
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi/addon.py", line 89, in <module>
                                                if login.login()==True:
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi/resources/login.py", line 31, in login
                                                post=post_data)
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi/resources/connect.py", line 91, in load_netflix_site
                                                session.headers = read_headers()
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi/resources/connect.py", line 80, in read_headers
                                                return pickle.loads(content)
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/pickle.py", line 1374, in loads
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/pickle.py", line 858, in load
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.10_x86_64-target/lib/python2.6/pickle.py", line 880, in load_eof
                                            EOFError
                                            -->End of Python script error report<--

**Comment by logi85** [comment]
please try again with 0.4.3

**Comment by jaraeez** [comment]
Still no go. After completely removing & installing the latest it won't even open the plugin & nothing gets populated in the '/Users/user1/Library/Application%20Support/Kodi/userdata/addon_data/plugin.video.flix2kodi/' folder other than the settings.xml. Cheers


12:50:01 T:4606521344  NOTICE: -->Python Interpreter Initialized<--
12:50:02 T:4606521344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named keyring
                                            Traceback (most recent call last):
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/addon.py", line 8, in <module>
                                                from resources import general
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/general.py", line 6, in <module>
                                                import add
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/add.py", line 10, in <module>
                                                from resources import library
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/library.py", line 9, in <module>
                                                import get
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/get.py", line 8, in <module>
                                                import login
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/login.py", line 7, in <module>
                                                import connect
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/connect.py", line 7, in <module>
                                                from resources import chrome_cookie
                                              File "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/chrome_cookie.py", line 16, in <module>
                                                import keyring
                                            ImportError: No module named keyring
                                            -->End of Python script error report<--

**Comment by logi85** [comment]
hi, please try again with 0.4.5 ;-) we'll find a solution, even for mac! ;-)

**Comment by jaraeez** [comment]
So close now.. Logins in fine, searches fine etc. When I now go to play any vid the screen flicks back to the page I was on. Cheers

10:23:17 T:4598816768  NOTICE: Thread BackgroundLoader start, auto delete: false
10:23:18 T:4550299648  NOTICE: Previous line repeats 1 times.
10:23:18 T:4550299648  NOTICE: Thread LanguageInvoker start, auto delete: false
10:23:18 T:4550299648  NOTICE: -->Python Interpreter Initialized<--
10:23:19 T:4598816768  NOTICE: Thread BackgroundLoader start, auto delete: false
10:23:21 T:4550299648  NOTICE: Thread JobWorker start, auto delete: true
10:23:24 T:4598816768  NOTICE: Thread LanguageInvoker start, auto delete: false
10:23:24 T:4598816768  NOTICE: -->Python Interpreter Initialized<--
10:23:25 T:4598816768 WARNING: Attempt to use invalid handle -1
10:23:25 T:4507688960  NOTICE: Found 1 Lists of Devices
10:23:25 T:4507688960  NOTICE: Enumerated DARWINOSX devices:
10:23:25 T:4507688960  NOTICE:     Device 1
10:23:25 T:4507688960  NOTICE:         m_deviceName      : default
10:23:25 T:4507688960  NOTICE:         m_displayName     : Default
10:23:25 T:4507688960  NOTICE:         m_displayNameExtra: HDMI
10:23:25 T:4507688960  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
10:23:25 T:4507688960  NOTICE:         m_channels        : FL,FR
10:23:25 T:4507688960  NOTICE:         m_sampleRates     : 48000,44100,32000
10:23:25 T:4507688960  NOTICE:         m_dataFormats     : AE_FMT_S24LE3,AE_FMT_AC3,AE_FMT_DTS,AE_FMT_S16LE
10:23:25 T:4507688960  NOTICE:     Device 2
10:23:25 T:4507688960  NOTICE:         m_deviceName      : AirPlay:stream0:source0
10:23:25 T:4507688960  NOTICE:         m_displayName     : AirPlay
10:23:25 T:4507688960  NOTICE:         m_displayNameExtra: MacXBMC (7)
10:23:25 T:4507688960  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
10:23:25 T:4507688960  NOTICE:         m_channels        : FL,FR
10:23:25 T:4507688960  NOTICE:         m_sampleRates     : 44100
10:23:25 T:4507688960  NOTICE:         m_dataFormats     : AE_FMT_S16LE
10:23:25 T:4507688960  NOTICE:     Device 3
10:23:25 T:4507688960  NOTICE:         m_deviceName      : AirPlay:stream0:source1
10:23:25 T:4507688960  NOTICE:         m_displayName     : AirPlay
10:23:25 T:4507688960  NOTICE:         m_displayNameExtra: AppleTV2
10:23:25 T:4507688960  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
10:23:25 T:4507688960  NOTICE:         m_channels        : FL,FR
10:23:25 T:4507688960  NOTICE:         m_sampleRates     : 44100
10:23:25 T:4507688960  NOTICE:         m_dataFormats     : AE_FMT_S16LE
10:23:25 T:4507688960  NOTICE:     Device 4
10:23:25 T:4507688960  NOTICE:         m_deviceName      : Built-in Output:stream0
10:23:25 T:4507688960  NOTICE:         m_displayName     : Built-in Output
10:23:25 T:4507688960  NOTICE:         m_displayNameExtra: Internal Speakers
10:23:25 T:4507688960  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
10:23:25 T:4507688960  NOTICE:         m_channels        : FL,FR
10:23:25 T:4507688960  NOTICE:         m_sampleRates     : 96000,88200,48000,44100
10:23:25 T:4507688960  NOTICE:         m_dataFormats     : AE_FMT_S24LE3,AE_FMT_S16LE,AE_FMT_FLOAT
10:23:25 T:4507688960  NOTICE:     Device 5
10:23:25 T:4507688960  NOTICE:         m_deviceName      : HDMI:stream0
10:23:25 T:4507688960  NOTICE:         m_displayName     : HDMI
10:23:25 T:4507688960  NOTICE:         m_displayNameExtra: VE247
10:23:25 T:4507688960  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
10:23:25 T:4507688960  NOTICE:         m_channels        : FL,FR
10:23:25 T:4507688960  NOTICE:         m_sampleRates     : 48000,44100,32000
10:23:25 T:4507688960  NOTICE:         m_dataFormats     : AE_FMT_S24LE3,AE_FMT_AC3,AE_FMT_DTS,AE_FMT_S16LE
10:23:25 T:4507688960  NOTICE:     Device 6
10:23:25 T:4507688960  NOTICE:         m_deviceName      : Soundflower (2ch):stream0
10:23:25 T:4507688960  NOTICE:         m_displayName     : Soundflower (2ch)
10:23:25 T:4507688960  NOTICE:         m_displayNameExtra:
10:23:25 T:4507688960  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
10:23:25 T:4507688960  NOTICE:         m_channels        : FL,FR
10:23:25 T:4507688960  NOTICE:         m_sampleRates     : 192000,176400,96000,88200,48000,44100
10:23:25 T:4507688960  NOTICE:         m_dataFormats     : AE_FMT_S32BE
10:23:25 T:4507688960  NOTICE:     Device 7
10:23:25 T:4507688960  NOTICE:         m_deviceName      : Soundflower (64ch):stream0
10:23:25 T:4507688960  NOTICE:         m_displayName     : Soundflower (64ch)
10:23:25 T:4507688960  NOTICE:         m_displayNameExtra:
10:23:25 T:4507688960  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
10:23:25 T:4507688960  NOTICE:         m_channels        : UNKNOWN1,UNKNOWN2,UNKNOWN3,UNKNOWN4,UNKNOWN5,UNKNOWN6,UNKNOWN7,UNKNOWN8,UNKNOWN9,UNKNOWN10,UNKNOWN11,UNKNOWN12,UNKNOWN13,UNKNOWN14,UNKNOWN15,UNKNOWN16
10:23:25 T:4507688960  NOTICE:         m_sampleRates     : 192000,176400,96000,88200,48000,44100
10:23:25 T:4507688960  NOTICE:         m_dataFormats     : AE_FMT_S32BE
10:23:25 T:4508225536  NOTICE: Initialize pseudo device - requesting stream 0
10:23:25 T:4735504384  NOTICE: Thread LanguageInvoker start, auto delete: false
10:23:25 T:4735504384  NOTICE: -->Python Interpreter Initialized<--
10:23:25 T:140735259591424   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
10:23:25 T:4736040960  NOTICE: Thread BackgroundLoader start, auto delete: false
10:23:25 T:4736577536  NOTICE: Thread LanguageInvoker start, auto delete: false
10:23:26 T:4736577536  NOTICE: -->Python Interpreter Initialized<--

**Comment by logi85** [comment]
hi, changed to profilE, thx.
please switch to chrome and try again and have a look into the log. safari support is not currently implemented. If chrome works we could add safari. I have no mac so it's a little difficult ;-)

**Comment by jaraeez** [comment]
No worries with Safari I don't use it myself.
I updated & change to Chrome unfortunately I have the exact same problem & the log looks the same.

10:18:27 T:4699164672  NOTICE: Thread LanguageInvoker start, auto delete: false
10:18:27 T:140735259591424   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
10:18:28 T:4699164672  NOTICE: -->Python Interpreter Initialized<--
10:18:28 T:4718071808  NOTICE: Thread BackgroundLoader start, auto delete: false
10:18:28 T:4718608384  NOTICE: Thread LanguageInvoker start, auto delete: false
10:18:28 T:4718608384  NOTICE: -->Python Interpreter Initialized<--

**Comment by logi85** [comment]
hi, please try to launch  /Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/scripts/launcher/darwin/chrome.sh from terminal I think there is the problem that there is a bug in the script

**Comment by Avishitrit** [comment]
I have see the same exact error on mac as well. Tried to run the script on the shell and opens chrome but the only this is that I need to add "\" because of the space in application support folder name. 

But In the log I can't see that it's running with the "\"
This is how I run it from the terminal:
/Users/user1/Library/Application\ Support/Kodi/addons/plugin.video.flix2kodi/resources/scripts/launcher/darwin/chrome.sh

**Comment by logi85** [comment]
ok so if you add the backslash to the script chrome still comes not up?

**Comment by Avishitrit** [comment]
to which script I should add it?

**Comment by logi85** [comment]
ah sorry, read to fast. but you could try to call this in terminal:
sh "/Users/user1/Library/Application Support/Kodi/addons/plugin.video.flix2kodi-master/resources/scripts/launcher/darwin/chrome.sh" 
as this is the way the addon launches the script

**Comment by Avishitrit** [comment]
not working also. Only with the backslash.

**Comment by logi85** [comment]
and without? (but with double-quotes)

**Comment by Avishitrit** [comment]
without the backslash it's not working. Tried with double-quota and a single quote as it not running the script.

**Comment by logi85** [comment]
ah okay, in a few minutes I'll release a new version with \ in call. drink a coffee and then watch a movie on netflix ;-)

**Comment by Avishitrit** [comment]
awesome! thanks a lot :)

**Comment by logi85** [comment]
I guess it was a loooong cofffee, please try with 0.4.7

**Comment by jaraeez** [comment]
Woke up this morning (Australia) & saw a flurry of activity :)
Well Sir I take my hat off to you all seems to now be working fine (not checked out all folders) & I owe you a drink.

'Thank You'

**Comment by logi85** [comment]
If I'm ever in Australia, I'll call you ;-)

**Comment by Avishitrit** [comment]
just had a chance to check it now and it's working amazing! thanks a lot!!

**Comment by logi85** [comment]
fine, you're welcome!
