### ISSUE TITLE
Plugin fails to launch

### ISSUE THREAD

**Issue by stafio** [logi85/plugin.video.flix2kodi#20]
I had installed the plugin earlier and it was working, although I'm not sure exactly what version it was at when I first installed it. Running the latest version, the plugin fails to launch. The error seems to be related to python cryptography. Running Lubuntu 15.10, I tried installing python-cryptography and python3-cryptography and neither of those solved the problem.

I also tried following the steps at http://forum.kodi.tv/showthread.php?tid=254263 under " - I get the error "Error Contents: osrandom engine already registered" in logfile". The package "pip" does not exist, so I had to to apt-get install python-pip. After running " sudo pip install cryptographic" the following was returned:
"Downloading/unpacking cryptographic
  Could not find any downloads that satisfy the requirement cryptographic
Cleaning up...
No distributions at all found for cryptographic"

From the log:
19:16:15 T:140658501220096   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named Crypto.Cipher
                                            Traceback (most recent call last):
                                              File "/home/kevin/.kodi/addons/plugin.video.flix2kodi/addon.py", line 8, in <module>
                                                from resources import general
                                              File "/home/kevin/.kodi/addons/plugin.video.flix2kodi/resources/general.py", line 6, in <module>
                                                import add
                                              File "/home/kevin/.kodi/addons/plugin.video.flix2kodi/resources/add.py", line 10, in <module>
                                                from resources import library
                                              File "/home/kevin/.kodi/addons/plugin.video.flix2kodi/resources/library.py", line 9, in <module>
                                                import get
                                              File "/home/kevin/.kodi/addons/plugin.video.flix2kodi/resources/get.py", line 9, in <module>
                                                from resources import connect
                                              File "/home/kevin/.kodi/addons/plugin.video.flix2kodi/resources/connect.py", line 8, in <module>
                                                from resources import chrome_cookie
                                              File "/home/kevin/.kodi/addons/plugin.video.flix2kodi/resources/chrome_cookie.py", line 23, in <module>
                                                from Crypto.Cipher import AES
                                            ImportError: No module named Crypto.Cipher
                                            -->End of Python script error report<--
19:16:16 T:140659944044288  NOTICE: -->Python Interpreter Initialized<--
19:16:16 T:140661495158848   ERROR: GetDirectory - Error getting plugin://plugin.video.flix2kodi/
19:16:16 T:140661495158848   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.flix2kodi/) failed

**Comment by logi85** [comment]
Hi, just do:
sudo apt-get install python-crypto

**Comment by stafio** [comment]
Thanks, that worked. I don't know how I saw the python-cryptography packages, but not this one. It may be good to include this as a note in the requirements/setup if you haven't already.

**Comment by logi85** [comment]
thx for reply. added to faq.
