### ISSUE TITLE
Flix2kodi crashes when adding a movie to My List

### ISSUE THREAD

**Issue by benno1973** [logi85/plugin.video.flix2kodi#21]
When I search for a movie and then attempt to add that movie to My List using the context menu, I get an error saying Flix2Kodi has crashed, do you wish to reattempt to Login?

Running Kodi 15.2 on Win7 SP1.

Log as follows:

[Flix2Kodi_MyListCrash.txt](https://github.com/logi85/plugin.video.flix2kodi/files/80716/Flix2Kodi_MyListCrash.txt)

**Comment by logi85** [comment]
adding should now work, please have a look to forum. removing will be the next step.

**Comment by benno1973** [comment]
Unable to test - 0.4.8 crashes as soon as I select 'Movie' or 'TV Show'. Requests re-login which seems successful, but can't get further than that. Error log:

08:30:39 T:5196  NOTICE: -->Python Interpreter Initialized<--
08:30:39 T:5196  NOTICE: [plugin.video.flix2kodi] Loading netflix: https://www.netflix.com/ Post: None
08:30:42 T:5196  NOTICE: [plugin.video.flix2kodi] Loading netflix: https://www.netflix.com/Login Post: None
08:30:43 T:2804  NOTICE: libspotify: notified main thread
08:30:43 T:5196  NOTICE: [plugin.video.flix2kodi] Loading netflix: https://www.netflix.com/Login?locale=en-AU Post: {u'RememberMe': u'on', u'authURL': '1452212781419.vea1rGS96qqr9xcTpSiz9t0XUjk=', u'password': 'AnnaBrown', u'email': 'benmorris1973@gmail.com'}
08:30:46 T:5196  NOTICE: [plugin.video.flix2kodi] parameters: ?mode=main&thumb&type=tv&url
08:30:46 T:5196   ERROR: [plugin.video.flix2kodi] Traceback (most recent call last):
                                              File "C:\Users\mce\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\addon.py", line 84, in <module>
                                                handle_request()
                                              File "C:\Users\mce\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\addon.py", line 36, in handle_request
                                                general.main(video_type)
                                              File "C:\Users\mce\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\resources\general.py", line 40, in main
                                                add_dynamic_lists(video_type)
                                              File "C:\Users\mce\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\resources\general.py", line 30, in add_dynamic_lists
                                                content = connect.load_netflix_site("https://www.netflix.com/")
                                              File "C:\Users\mce\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\resources\connect.py", line 110, in load_netflix_site
                                                if do_login():
                                              File "C:\Users\mce\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\resources\connect.py", line 188, in do_login
                                                return login.login()
                                              File "C:\Users\mce\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\resources\login.py", line 32, in login
                                                post=post_data, login_process=True)
                                              File "C:\Users\mce\AppData\Roaming\Kodi\addons\plugin.video.flix2kodi\resources\connect.py", line 120, in load_netflix_site
                                                raise ValueError('!HTTP-ERROR!: '+str(status_code)+' loading: "'+url+'", post: "'+ str(post)+'"')
                                            ValueError: !HTTP-ERROR!: 200 loading: "https://www.netflix.com/Login?locale=en-AU", post: "{u'RememberMe': u'on', u'authURL': '1452212781419.vea1rGS96qqr9xcTpSiz9t0XUjk=', u'password': 'XXXX', u'email': 'XXXX@gmail.com'}"

**Comment by logi85** [comment]
please try again with 0.4.9

**Comment by benno1973** [comment]
All working now, thanks.
