### ISSUE TITLE
not work on my kodi opensuse 13.2  ?

### ISSUE THREAD

**Issue by manuelsongokuh** [logi85/plugin.video.flix2kodi#38]
hi
i try install addons for kodi netflix. i add email and password and start the video addons and not work and window error said error in log but where i will read log?
kodi 16.0

**Comment by bolens1112** [comment]
I am having a similar issue.  When trying to do list any movies or TV Shows with the addon an error of: Plugin crashed do you want to login pops up. Having it refresh the login does not fix the issue as the same box pops back up.
Ubuntu Linux.
Chrome.
Flix2kodi v. 0.6.0

Log:
`20:58:59 T:140257727084288   ERROR: [plugin.video.flix2kodi] Traceback (most recent call last):
                                              File "/home/jon/.kodi/addons/plugin.video.flix2kodi/addon.py", line 83, in <module>
                                                handle_request()
                                              File "/home/jon/.kodi/addons/plugin.video.flix2kodi/addon.py", line 47, in handle_request
                                                list.viewing_activity(video_type, run_as_widget)
                                              File "/home/jon/.kodi/addons/plugin.video.flix2kodi/resources/list.py", line 55, in viewing_activity
                                                metadata = get.viewing_activity_matches(video_type)
                                              File "/home/jon/.kodi/addons/plugin.video.flix2kodi/resources/get.py", line 30, in viewing_activity_matches
                                                content = viewing_activity_info()
                                              File "/home/jon/.kodi/addons/plugin.video.flix2kodi/resources/get.py", line 287, in viewing_activity_info
                                                'authorization_url')))
                                              File "/home/jon/.kodi/addons/plugin.video.flix2kodi/resources/connect.py", line 122, in load_netflix_site
                                                ret, status_code = load_site_internal(url, session, post, netflix=True, options=False)
                                              File "/home/jon/.kodi/addons/plugin.video.flix2kodi/resources/connect.py", line 211, in load_site_internal
                                                response = session.get(url, headers=headers, cookies=cookies, verify=False)
                                              File "/home/jon/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 480, in get
                                                return self.request('GET', url, **kwargs)
                                              File "/home/jon/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 454, in request
                                                prep = self.prepare_request(req)
                                              File "/home/jon/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 388, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/home/jon/.kodi/addons/script.module.requests/lib/requests/models.py", line 293, in prepare
                                                self.prepare_url(url, params)
                                              File "/home/jon/.kodi/addons/script.module.requests/lib/requests/models.py", line 353, in prepare_url
                                                raise MissingSchema(error)
                                            MissingSchema: Invalid URL '/viewingactivity?_retry=0&authURL=1461113935849.lQdD2eHM4X3b/lZPMgXnaXsj0+I=': No schema supplied. Perhaps you meant http:///viewingactivity?_retry=0&authURL=1461113935849.lQdD2eHM4X3b/lZPMgXnaXsj0+I=?
`

**Comment by logi85** [comment]
it seams that the api-url is missing. are you using newest version? (you should use 0.6.1)
are there other errors (especially if you do a (re)login) in logfile?

**Comment by manuelsongokuh** [comment]
hello
i tried addons flix2kodi but is error and not work version 0.6.2...i dont know why..but worked to installed kodi, i did add my account and password and start..nothing there are error..

**Comment by logi85** [comment]
perhaps fixed in new release. please check. will release in a few hours.
