### ISSUE TITLE
Addon stopped working

### ISSUE THREAD

**Issue by Dschinghis-Kahn** [logi85/plugin.video.flix2kodi#42]
Cannot login to my account and/or open any link/folder in the GUI.
Kodi.log shows:
20:22:02 T:140269494343424   ERROR: [plugin.video.flix2kodi] Traceback (most recent call last):
                                              File "/home/media/.kodi/addons/plugin.video.flix2kodi/addon.py", line 83, in <module>
                                                handle_request()
                                              File "/home/media/.kodi/addons/plugin.video.flix2kodi/addon.py", line 37, in handle_request
                                                general.main(video_type)
                                              File "/home/media/.kodi/addons/plugin.video.flix2kodi/resources/general.py", line 46, in main
                                                root_list = lolomos.get_root_list()
                                              File "/home/media/.kodi/addons/plugin.video.flix2kodi/resources/path_evaluator/types/lolomos.py", line 40, in get_root_list
                                                return get_root_list_id_from_cookie()
                                              File "/home/media/.kodi/addons/plugin.video.flix2kodi/resources/path_evaluator/__init__.py", line 68, in get_root_list_id_from_cookie
                                                raise ValueError('root_list_id not found in cookies!')
                                            ValueError: root_list_id not found in cookies!

**Comment by cy8aer** [comment]
same for me. German Netflix

**Comment by bhaal2** [comment]
same here don't get a list of users...

**Comment by logi85** [comment]
fixed.

**Comment by Dschinghis-Kahn** [comment]
Thanks, now it works again .

**Comment by cy8aer** [comment]
I am sorry, even with 0.6.2 it does not wor for me. Empty user list here.

**Comment by nlowe** [comment]
Same issue for me

**Comment by KingBowser** [comment]
Issue returned.

**Comment by kirkvanslyke** [comment]
Yes, This has happened to me as well. Was working great about a week ago.

**Comment by kirkvanslyke** [comment]
This looks to be fixed now! Checked for addon updates. There was one available for Flix2kodi, and it's working great again. Thanks logi85!!

**Comment by nlowe** [comment]
I'm not seeing any updates (on `0.6.6`)

**Comment by kirkvanslyke** [comment]
Yes. Previously, I had 0.6.5 which had the problem.

**Comment by kirkvanslyke** [comment]
OK. Well... after updating with 0.6.6, it worked for all of ... 2 days :-( 
Back to the same issue again.
