### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by logi85** [logi85/plugin.video.flix2kodi#52]
22:56:22 T:139673742505728   ERROR: [plugin.video.flix2kodi] Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/addon.py", line 85, in <module>
                                                handle_request()
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/addon.py", line 63, in handle_request
                                                search.netflix(video_type, url)
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/search.py", line 15, in netflix
                                                list.search(search_string, video_type)
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/list.py", line 149, in search
                                                metadatas = get.videos_in_search(search_string)
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/get.py", line 125, in videos_in_search
                                                video_id, vjsn = deref(search_node[video_ref], ret)
                                              File "/home/kodi/.kodi/addons/plugin.video.flix2kodi/resources/path_evaluator/__init__.py", line 106, in deref
                                                raise ValueError(str(layer)+' not found in: '+str(jsn))
                                            ValueError: current not found in: {u'search': {u'the': {u'24': {u'current': {}, u'seasonList': {u'current': {}},$
22:56:22 T:139673742505728  NOTICE: [plugin.video.flix2kodi] Loading netflix: https://www.netflix.com/Login Post: None

**Comment by duck7000** [comment]
Hi

Any luck to solve this?
This addon is the most usefull netflix solution that i.ve found!
