### ISSUE TITLE
Issue with Loading Movies

### ISSUE THREAD

**Issue by kuojo** [logi85/plugin.video.flix2kodi#59]
Everytime I go to load a movie this exception gets thrown.

`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: lolomos not found in: {}
                                            Traceback (most recent call last):
                                              File "/home/aryn/.kodi/addons/plugin.video.flix2kodi/addon.py", line 91, in <module>
                                                handle_request()
                                              File "/home/aryn/.kodi/addons/plugin.video.flix2kodi/addon.py", line 37, in handle_request
                                                general.main(video_type)
                                              File "/home/aryn/.kodi/addons/plugin.video.flix2kodi/resources/general.py", line 50, in main
                                                mylist = lolomos.get_mylist(root_list)
                                              File "/home/aryn/.kodi/addons/plugin.video.flix2kodi/resources/path_evaluator/types/lolomos.py", line 54, in get_mylist
                                                llms = child('lolomos', ret)
                                              File "/home/aryn/.kodi/addons/plugin.video.flix2kodi/resources/path_evaluator/__init__.py", line 98, in child
                                                raise ValueError(str(chld)+' not found in: '+str(jsn))
                                            ValueError: lolomos not found in: {}
                                            -->End of Python script error report<--
`

Chrome is installed and kodi is running in openbox

This part of the debug log just above the exception 
`
NOTICE: [plugin.video.flix2kodi] Loading netflix: https://www.netflix.com/api/shakti/pathEvaluator/a53eb25ebe6cb9bf8953cff2838686fd114bccb2?materialize=true&model=harris Post: {"paths":[["lolomos","ff3e37de-ae2d-4ff1-9410-da065088d389_ROOT","mylist"],["lolomos","ff3e37de-ae2d-4ff1-9410-da065088d389_ROOT",{"from":0,"to":99},"displayName"]],"authURL":"1480792181798.KizhxMmBJcUqhE8G251QknkF7N8="}
12:09:34 T:140433912997632
`

**Comment by fkmclane** [comment]
You might want to redact the `authURL` and the `<GUID>_ROOT` portions of your issue since those are sensitive information. I'm looking into the issue now so you can expect a fix over the next day or two.

**Comment by fkmclane** [comment]
The first thing that needs to be changed is that the request should have `Content-Type: application/json` set in the headers.

I poked around the "lolomos" API and I think it need to be requested and parsed differently. As far as the request goes, it should look something like `{"paths":[["lolomos","<GUID>_ROOT","mylist",{"from":0."to":99},"title"]], "authUrl":"<timestamp>.<base64_auth>"}` and the response should look something like the JSON below. More can be requested than just `"title"` by replacing with a list, i.e. `["summary", "title"]`. Additionally different lists can be request in place of `"mylist"`, such as `"netflixOriginals"`. I might reimplement `lolomos.py` to account for these changes or see if @logi85 logi85 would like to spare me the time and write it himself.

```json
{
    "value": {
        "lolomos": {
            "[REDACTED]_ROOT": {
                "mylist": [
                    "lolomos",
                    "[REDACTED]_ROOT",
                    "1"
                ],
                "1": [
                    "lists",
                    "[REDACTED]_18061991"
                ]
            }
        },
        "lists": {
            "[REDACTED]_18061991": {
                "0": [
                    "videos",
                    "80077417"
                ],
                "1": [
                    "videos",
                    "80074220"
                ],
                "2": [
                    "videos",
                    "70172488"
                ],
                "3": [
                    "videos",
                    "70136118"
                ],
                "4": [
                    "videos",
                    "70307663"
                ],
                "5": [
                    "videos",
                    "880640"
                ],
                "6": [
                    "videos",
                    "80092885"
                ],
                "7": [
                    "videos",
                    "70153380"
                ],
                "8": [
                    "videos",
                    "60034782"
                ],
                "9": [
                    "videos",
                    "80029820"
                ],
                "10": [
                    "videos",
                    "902003"
                ],
                "11": [
                    "videos",
                    "70136140"
                ],
                "12": [
                    "videos",
                    "60034545"
                ],
                "13": [
                    "videos",
                    "70202589"
                ],
                "14": [
                    "videos",
                    "80025744"
                ],
                "15": [
                    "videos",
                    "70158329"
                ],
                "16": [
                    "videos",
                    "17405997"
                ],
                "17": [
                    "videos",
                    "80023289"
                ],
                "18": [
                    "videos",
                    "247351"
                ],
                "19": [
                    "videos",
                    "70241953"
                ],
                "20": [
                    "videos",
                    "70056431"
                ],
                "21": [
                    "videos",
                    "70202753"
                ],
                "22": [
                    "videos",
                    "70143825"
                ],
                "23": [
                    "videos",
                    "70202128"
                ],
                "24": [
                    "videos",
                    "70140458"
                ],
                "25": [
                    "videos",
                    "70264888"
                ],
                "26": [
                    "videos",
                    "80057281"
                ],
                "27": [
                    "videos",
                    "70158331"
                ],
                "28": [
                    "videos",
                    "70299043"
                ],
                "29": [
                    "videos",
                    "60020330"
                ],
                "30": [
                    "videos",
                    "60000207"
                ],
                "31": [
                    "videos",
                    "70140353"
                ],
                "32": [
                    "videos",
                    "60010202"
                ],
                "33": [
                    "videos",
                    "70158332"
                ],
                "34": [
                    "videos",
                    "80029103"
                ],
                "35": [
                    "videos",
                    "70208248"
                ],
                "36": [
                    "videos",
                    "80043576"
                ],
                "37": [
                    "videos",
                    "70140439"
                ],
                "38": [
                    "videos",
                    "70293789"
                ],
                "39": [
                    "videos",
                    "80057578"
                ],
                "40": [
                    "videos",
                    "70265224"
                ],
                "41": [
                    "videos",
                    "70185014"
                ],
                "60": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "83": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "53": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "99": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "57": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "95": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "76": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "71": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "94": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "90": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "49": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "68": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "45": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "64": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "87": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "82": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "52": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "79": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "56": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "75": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "98": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "70": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "93": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "48": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "67": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "63": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "44": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "86": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "81": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "59": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "78": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "51": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "74": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "55": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "97": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "92": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "50": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "43": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "66": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "89": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "47": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "62": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "85": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "80": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "61": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "54": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "77": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "58": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "73": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "96": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "91": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "72": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "42": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "88": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "69": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "46": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "84": {
                    "_sentinel": true,
                    "$type": "sentinel"
                },
                "65": {
                    "_sentinel": true,
                    "$type": "sentinel"
                }
            }
        },
        "videos": {
            "80077417": {
                "title": "Colony"
            },
            "80074220": {
                "title": "3%"
            },
            "70172488": {
                "title": "The Twilight Zone (Original Series)"
            },
            "70136118": {
                "title": "Lost"
            },
            "70307663": {
                "title": "The Giver"
            },
            "880640": {
                "title": "Pulp Fiction"
            },
            "80092885": {
                "title": "ARQ"
            },
            "70153380": {
                "title": "Futurama"
            },
            "60034782": {
                "title": "Primer"
            },
            "80029820": {
                "title": "Ascension"
            },
            "902003": {
                "title": "Reservoir Dogs"
            },
            "70136140": {
                "title": "Star Trek"
            },
            "60034545": {
                "title": "Eternal Sunshine of the Spotless Mind"
            },
            "70202589": {
                "title": "Sherlock"
            },
            "80025744": {
                "title": "Sense8"
            },
            "70158329": {
                "title": "Star Trek: The Next Generation"
            },
            "17405997": {
                "title": "Good Will Hunting"
            },
            "80023289": {
                "title": "Dark Matter"
            },
            "247351": {
                "title": "Amadeus"
            },
            "70241953": {
                "title": "Revolution"
            },
            "70056431": {
                "title": "Hot Fuzz"
            },
            "70202753": {
                "title": "Firefly"
            },
            "70143825": {
                "title": "Supernatural"
            },
            "70202128": {
                "title": "Tinker, Tailor, Soldier, Spy"
            },
            "70140458": {
                "title": "Torchwood"
            },
            "70264888": {
                "title": "Black Mirror"
            },
            "80057281": {
                "title": "Stranger Things"
            },
            "70158331": {
                "title": "Star Trek: Voyager"
            },
            "70299043": {
                "title": "Attack on Titan"
            },
            "60020330": {
                "title": "Journey to the Center of the Earth"
            },
            "60000207": {
                "title": "Sleepy Hollow"
            },
            "70140353": {
                "title": "Alfred Hitchcock Presents"
            },
            "60010202": {
                "title": "Cape Fear"
            },
            "70158332": {
                "title": "Star Trek: Enterprise"
            },
            "80029103": {
                "title": "Brain Games"
            },
            "70208248": {
                "title": "J. Edgar"
            },
            "80043576": {
                "title": "AJIN: Demi-Human"
            },
            "70140439": {
                "title": "Sliders"
            },
            "70293789": {
                "title": "Philomena"
            },
            "80057578": {
                "title": "The Little Prince"
            },
            "70265224": {
                "title": "Upstream Color"
            },
            "70185014": {
                "title": "Alphas"
            }
        }
    },
    "paths": [
        [
            "lolomos",
            "[REDACTED]_ROOT",
            "mylist",
            {
                "from": 0,
                "to": 99
            },
            "title"
        ]
    ]
}
```

**Comment by tboulogne** [comment]
@fkmclane hello,could you post your modified lolomos.py please ?

**Comment by mrwensveen** [comment]
I'm experiencing this as well. Is there any way I can help (provide data or do some experimentation). I've never done Python, but it looks doable :)

**Comment by fkmclane** [comment]
I've not made a modified file yet (and I would have made a pull request if I had). As far as changes go, first the 'Content-Type' header needs to be set to 'application/json'. Netflix no longer responds to requests without it.

I poked around the API for a bit and I don't think that file is currently parsing lists correctly. I posted example responses from the API and the file should probably be adapted to pick out ids and titles from the list.
